HelloDjango/HelloDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls import url
from HelloDjango import settings
from exel.views import *
from django.views.static import serve as mediaserve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('exel.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        url(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
            mediaserve, {'document_root': settings.MEDIA_ROOT}),
        url(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
            mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

HelloDjango/exel/urls.py
from django.urls import path, re_path
from . import views
from .views import *

app_name = 'exel'

urlpatterns = [
    path('', Prepare_calc.as_view(), name='prepare'),
    path('calculate/<int:pk>/', views.calculate, name='calculate'),
]

'''
path('', views.main, name='main'),
path('prepare/calculate/<int:pk>/', views.calculate, name='calculate'),
path('cleared/<int:pk>/', views.cleared, name='but_cleared'),
path('cleared/utm/<int:pk>/', views.utm, name='utm'),
path('cleared/materials/<int:pk>/', views.materials, name='materials'),
path('cleared/complete/<int:pk>/', views.complete, name='complete'),
path('not_cleared/<int:pk>/', views.not_cleared, name='but_not_cleared'),
path('download/', Download_calc.as_view(), name='download_calc'),
path('prepare/', Prepare_calc.as_view(), name='prepare'),
path('buying/', Buying.as_view(), name='buying'),
path('buying_priority/', Dmp_buying.as_view(), name='dmp'),
path('account/login/', Login.as_view(), name='login'),
#path('account/register/', RegisterView.as_view(), name='register'),
path('logout/', views.Logout, name='logout'),
'''

exel/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import LoginView
from .views import *

app_name = 'exel'

urlpatterns = [
    path('', views.main, name='main'),
    path('prepare/calculate/', views.calculate, name='calculate'),
    path('cleared/', views.cleared, name='but_cleared'),
    path('cleared/utm/', views.utm, name='utm'),
    path('cleared/materials/', views.materials, name='materials'),
    path('report/', views.report, name='report'),
    path('cleared/complete/', views.complete, name='complete'),
    path('not_cleared/', views.not_cleared, name='but_not_cleared'),
    path('download/', Download_calc.as_view(), name='download_calc'),
    path('prepare/', Prepare_calc.as_view(), name='prepare'),
    path('buying/', Buying.as_view(), name='buying'),
    path('account/login/', LoginView.as_view(), name='login'),
    path('account/register/', RegisterView.as_view(), name='register'),
    path('logout/', views.Logout, name='logout'),
]

'''
path('', views.main, name='main'),
path('prepare/calculate/<int:pk>/', views.calculate, name='calculate'),
path('cleared/<int:pk>/', views.cleared, name='but_cleared'),
path('cleared/utm/<int:pk>/', views.utm, name='utm'),
path('cleared/materials/<int:pk>/', views.materials, name='materials'),
path('cleared/complete/<int:pk>/', views.complete, name='complete'),
path('not_cleared/<int:pk>/', views.not_cleared, name='but_not_cleared'),
path('download/', Download_calc.as_view(), name='download_calc'),
path('prepare/', Prepare_calc.as_view(), name='prepare'),
path('buying/', Buying.as_view(), name='buying'),
path('buying_priority/', Dmp_buying.as_view(), name='dmp'),
path('account/login/', Login.as_view(), name='login'),
#path('account/register/', RegisterView.as_view(), name='register'),
path('logout/', views.Logout, name='logout'),
'''

planer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('office/', include('exel.urls')),
    path('', include('client.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

HelloDjango/exel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from pathlib import Path
from .resources import ByingResource
from tablib import Dataset
from django.core.exceptions import MultipleObjectsReturned
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.base import ContentFile
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView, LogoutView
from .models import *
from django.urls import reverse
from .forms import *
from django.contrib.auth import authenticate, login
from django.views.generic.base import *
from django.views.generic import *
from django.conf import settings
from django.contrib import messages
import pandas as pd
import openpyxl
import codecs
import os
import io
import uuid
import datetime
import math
from django.http import FileResponse
from os.path import join
from openpyxl.styles import Alignment, Border, Side, PatternFill, Font
from openpyxl import load_workbook
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.utils.dataframe import dataframe_to_rows
from django.core.mail import send_mail
from tablib import Dataset
from transliterate.decorators import transliterate_function
import http.client
import subprocess
from openpyxl.utils.cell import get_column_letter
from openpyxl.comments import Comment
from openpyxl.utils.cell import coordinate_from_string, column_index_from_string

@transliterate_function(language_code='ru', reversed=True)
def translit(text):
    return text


def main(request, super_us = False):
    if request.user.is_authenticated:
        username = request.user.username
        data = {
            'files': Client.objects.filter(username=username)[::-1],
            'cleared': Cleared.objects.filter(username=username)[::-1],
            'complete': Complete.objects.filter(username=username)[::-1],
                }
        if request.user.is_superuser == 1:
            data['body'] = 'on'
            return render(request, 'base.html', data)
        data['body'] = 'off'

        hol = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

        if not os.path.exists(os.path.join(hol, f"media/clients/{translit(username)}")):
            os.mkdir(os.path.join(hol, f"media/clients/{translit(username)}"))

            r = Report.objects.all()[0]
            report_common = r.file.name

            wb = openpyxl.load_workbook(filename=os.path.join(hol, f"media/{report_common}"))

            w = wb.worksheets[0]
            sheet = wb.active
            wb.save(os.path.join(hol, f"media/clients/{translit(username)}/report.xlsx").replace('\\', '/'))
            try:
                try:
                    f = Profile.objects.get(bying_username=username)
                except ObjectDoesNotExist:
                    f = Profile.objects.get(manager_username=username)
                f.report_common = f"media/clients/{translit(username)}/report.xlsx"
                f.save()
            except:
                Profile.objects.create(bying_username=username, manager_username=username, report_common=f"media/clients/{translit(username)}/report.xlsx")
    else:
        return redirect('exel:login')
    return render(request, 'base.html', data)


class RegisterView(CreateView):
    form_class  = RegisterUserForm
    template_name = 'registration/register.html'

    def get_success_url(self):
        return reverse('exel:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))


class Login(LoginView):
    form_class  = AuthenticationForm
    template_name = 'registration/login.html'


    def get_context_data(self, *, object_list=None, **kwargs):
        subprocess.Popen('C:\\Windows\\System32\\cmd.exe')
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))
    def dispatch(self, request, *args, **kwargs):
        data = {

            }
        return main()

class Send_email(TemplateView):
    template_name = "registration/send_email.html"
    def dispatch(self, request, *args, **kwargs):
        send_mail('Тема', 'Тело письма', settings.EMAIL_HOST_USER, ['davydoval2005@gmail.com'])

class Change(TemplateView):
    template_name = "registration/change.html"
    def dispatch(self, request, *args, **kwargs):
        data = {
            }
        return redirect('exel:login')

def Logout(request):
    logout(request)
    return redirect('exel:login')



class Prepare_calc(TemplateView):
    template_name = "prepare_calculation/prepare.html"
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            username = request.user.username
        else:
            username = 'lida'
            dataclass = {
                'cl': set(Brief.objects.all().values_list('client', flat=True)),
                'n_rk' : set(Brief.objects.all().values_list('name_rk', flat=True)),
                'client': Brief.objects.filter(username=username)[::-1],
                'form': BriefForm,
                #'now' : Brief.objects.filter(username=username),
                }
            if request.method == 'POST':
                username = username
                discount = request.POST.get('discount')
                AK = request.POST.get('AK')
                DCM = request.POST.get('DCM')
                client = request.POST.get('client')
                product = request.POST.get('product')
                name_rk = request.POST.get('name_rk')
                posad = request.POST.get('posad')
                type_act = request.POST.get('type_act')
                country = request.POST.get('country')
                ca = request.POST.get('ca')
                #region = request.POST.get('region')
                #gender = request.POST.get('gender')
                #age = request.POST.get('age')
                #interes = request.POST.get('interes')
                #income = request.POST.get('income')
                #rek = request.POST.get('rek')
                #materials = request.POST.get('materials')
                #duration1 = request.POST.get('duration1')
                #duration2 = request.POST.get('duration2')
                #duration3 = request.POST.get('duration3')
                period_c = request.POST.get('period_c')
                period_p = request.POST.get('period_p')
                #budget = request.POST.get('budget')
                KPI = request.POST.get('KPI')
                #plan = request.POST.get('plan')
                #description = request.POST.get('description')
                #competitors = request.POST.get('competitors')
                #who_prep_materials = request.POST.get('who_prep_materials')

                form = BriefForm(request.POST, request.FILES)

                if form.is_valid():
                    ex = request.FILES.get('img')
                    try:
                        brif = Brief.objects.create(username=username, client=client, product=product,
                                         name_rk=name_rk, posad=posad,
                                         type_act=type_act, country=country, ca=ca,
                                         period_c=period_c, period_p=period_p,
                                         KPI=KPI, img=ex,
                                         discount=discount, AK=AK, DCM=DCM)
                    except (NameError, AttributeError):
                        s = Brief.objects.filter(username=username, client=client)[::-1][0]
                        k = s.img.name
                        brif = Brief.objects.create(username=username, client=client, product=product,
                                         name_rk=name_rk, posad=posad,
                                         type_act=type_act, country=country, ca=ca,
                                         period_c=period_c, period_p=period_p,
                                         KPI=KPI, img=k,
                                         discount=discount, AK=AK, DCM=DCM)
                    except Location.MultipleObjectsReturned:
                        pass


                datet = brif.duploaded_at.strftime('%x').replace('/', '.')
                # In the down def to create a file DMP.xlsx
                for i in Dmp.objects.all():
                    n = i.file.url[1:]
                hol = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                p = pd.read_excel(os.path.join(hol, n), engine='openpyxl',
                                     header=5)
                e = openpyxl.load_workbook(filename=os.path.join(hol, n), data_only=True)
                ws = e.worksheets[0]
                sheet = e.active

                head_dmp = {} #назв столбцов, где есть примечания и rows
                all_columns_com = {}

                with open(os.path.join(hol, "media/pattern/comments.txt"), 'r') as f:
                    for name in f.read().split():
                        col = column_index_from_string(coordinate_from_string(name)[0])
                        if head_dmp.get(sheet.cell(row=6, column=col).value):
                            head_dmp[sheet.cell(row=6, column=col).value].append(coordinate_from_string(name)[1] - 6)
                        else:
                            head_dmp[sheet.cell(row=6, column=col).value] = [coordinate_from_string(name)[1] - 6]
                        all_columns_com[sheet.cell(row=6, column=col).value] = col


exel/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
  <title>{% block title %}Главная{% endblock %}</title>
   <!-- Required meta tags  <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

    <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            

</head>
<body>

{% block content %}
<div class="container">

          <nav>
            <div class="nav-wrapper">
              <a href="#" class="brand-logo">Logo</a>
              <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'exel:prepare' %}">ПОДГОТОВИТЬ РАСЧЕТ</a></li>
                <li><a href="{% url 'exel:download_calc' %}">ЗАГРУЗИТЬ РАСЧЕТ</a></li>
                <li><a href="{% url 'exel:buying' %}" class="button">БАИНГ</a></li>
                <li><a href="{% url 'exel:report' %}" class="button">Отчеты</a></li>
                <li><a href="{% url 'exel:logout' %}">Выйти</a></li>
              </ul>
            </div>
          </nav>

          <div class="row">
            <div class="col s12 m6">
              <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                  <span class="card-title">Card Title</span>
                  <p>I am a very simple card. I am good at containing small bits of information.
                  I am convenient because I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                  <a href="#">This is a link</a>
                  <a href="#">This is a link</a>
                </div>
              </div>
            </div>
          </div>

          <ul class="collapsible">
            <li>
              <table class="collapsible-header">
                <tbody>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                </tbody>
              </table>
              <table class="collapsible-body">
                <tbody>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                </tbody>
              </table>
            </li>
          </ul>

          <ul class="collapsible" style="box-shadow:none;border: none;">
            <li style="box-shadow:none;">
              <table class="collapsible-header">
                <tbody>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                </tbody>
              </table>
              <table class="collapsible-body">
                <tbody>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                  <tr>
                    <td>fffffff</td>
                  </tr>
                </tbody>
              </table>
            </li>
          </ul>


          <form method="post" class="cleared">

            <div class="row">
              <div class="col-2">
                <p id="base">СОГЛАСОВАННЫЕ<br>ПЛАНЫ<br>ИНФО ПО ЗАПУСКУ,<br>СТАТУС ОТКРУТКИ</p>
              </div>
              <div class="col-10" id="form1">
            <div class="table-responsive">

            <table class="highlight">
            	<tbody>
                	{% for name in cleared %}
                    {% if forloop.counter < 4 %}
                      <tr scope="row">
                        <td><a href="{% url 'exel:but_cleared'%}" class="s1">{{name.client}}</a>
                        </td>
                        <td>
                        <div>
                          <a href="#" data-toggle="tooltip" title={{name.comments}}>этапы проекта</a>

                          <div class="tooltip bs-tooltip-top" role="tooltip">
                            <div class="arrow"></div>
                            <div class="tooltip-inner">
                              {{name.comments}}
                            </div>
                          </div>
                          </div>
                        </td>
                      </tr>
                    {% endif %}
                	{% endfor %}
            	</tbody>
            </table>

        </div>

          <div class="collapse" id="collapseExample">
            <div class="table-responsive">
              <table class="highlight">
              	<tbody>
                  {% for name in cleared %}
                      {% if forloop.counter >= 4 %}
                        <tr>
                          <td><a href="{% url 'exel:but_cleared' %}">{{name.client}}</a>
                          </td>
                          <td>
                          <div>
                            <a href="#" data-toggle="tooltip" title={{name.comments}}>этапы проекта</a>

                            <div class="tooltip bs-tooltip-top" role="tooltip">
                              <div class="arrow"></div>
                              <div class="tooltip-inner">
                                {{name.comments}}
                              </div>
                            </div>
                            </div>
                          </td>
                        </tr>
                      {% endif %}

                  {% endfor %}
                </tbody>
              </table>
          </div>
          </div>
</div>
</div>

<div class="row">
  <div class="col-2">
  </div>
  <div class="col-10">
    <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="background: #5A1EB8;border-radius: 20px;">
      ПОКАЗАТЬ/CКРЫТЬ
    </button>
  </div>
</div>

</form>



      <form method="post">
          {% csrf_token %}

        <div class="row">
          <div class="col-2">
            <p id="not_cl">НЕ СОГЛАСОВАННЫЕ<br>ПЛАНЫ/СТАТУС</p>
          </div>
          <div class="col-10" id="form1">
        <div class="table-responsive">

        <table class="highlight">
            	<tbody>

                {% for name in files %}
                  {% if forloop.counter < 4 %}
                    <tr scope="row">
                      <td><a href="{% url 'exel:but_not_cleared' %}">{{name.client}}</a>
                      </td>
                      <td>
                      <div>
                        <a href="#" data-toggle="tooltip" title={{name.comments}}>этапы проекта</a>

                        <div class="tooltip bs-tooltip-top" role="tooltip">
                          <div class="arrow"></div>
                          <div class="tooltip-inner">
                            {{name.comments}}
                          </div>
                        </div>
                        </div>
                      </td>
                      <td>
                          <a href="{{ name.calculation.url }}">Выгрузить</a>
                      </td>
                    </tr>
                  {% endif %}
                {% endfor %}


        </tbody>
      </table>

  </div>

  <div class="collapse multi-collapse" id="collapseNotClear">
    <div class="table-responsive">
      <table class="highlight">
        <tbody>
          {% for name in files %}
            {% if forloop.counter >= 4 %}
              <tr scope="row">
                <td><a href="{% url 'exel:but_not_cleared'%}">{{name.client}}</a>
                </td>
                <td>
                <div>
                  <a href="#" data-toggle="tooltip" title={{name.comments}}>этапы проекта</a>

                  <div class="tooltip bs-tooltip-top" role="tooltip">
                    <div class="arrow"></div>
                    <div class="tooltip-inner">
                      {{name.comments}}
                    </div>
                  </div>
                  </div>
                </td>
                <td>
                    <a href="{{ name.calculation.url }}">Выгрузить</a>
                </td>
              </tr>
            {% endif %}
          {% endfor %}
    </tbody>
</table>
</div>
</div>
</div>
</div>

<div class="row">
  <div class="col-2">
  </div>
  <div class="col-10">
    <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#collapseNotClear" role="button" aria-expanded="false" aria-controls="collapseNotClear"style="background: #5A1EB8;border-radius: 20px;">ПОКАЗАТЬ/CКРЫТЬ</a>
  </div>
</div>


    	</form>



      <form method="post">
          {% csrf_token %}

        <div class="row">
          <div class="col" id="form1">
            <div class="table-responsive">

            <table class="highlight">
                  <tbody>
                  		<tr scope="row" class="name">
                          	<td>Клиент</td>
                          	<td>Название РК</td>
                          	<td>Период</td>
                          	<td>Карточка проекта</td>
                          </tr>
              			{% for name in complete %}
                      {% if forloop.counter < 5 %}
                      	<tr scope="row">
                          <td width="25%">{{name.client}}</td>
                          <td width="25%">{{name.name_rk}}</td>
                          <td width="25%">{{name.period_c}} - {{name.period_p}}</td>
                            <td width="25%">
                                <a class="s3" href="{% url 'exel:but_cleared'%}">Карточка проекта</a>
                            </td>
                  		  </tr>
                      {% endif %}
                  	{% endfor %}
                  </tbody>
                </table>

            </div>


      <div class="collapse multi-collapse" id="collapseEnd">
      <div class="table-responsive">
      <table class="highlight">
        <tbody>

          {% for name in complete %}
            {% if forloop.counter >= 4 %}
              <tr scope="row">
                  <td width="25%">{{name.client}}</td>
                  <td width="25%">{{name.name_rk}}</td>
                  <td width="25%">{{name.period_c}} - {{name.period_p}}</td>
                    <td width="25%">
                        <a class="s3" href="{% url 'exel:but_cleared'%}">Карточка проекта</a>
                    </td>
              </tr>
            {% endif %}
          {% endfor %}
      </tbody>
      </table>
      </div>
      </div>
      </div>
      </div>

      <div class="row">
      <div class="col-1">
      </div>
      <div class="col-11">
      <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#collapseEnd" role="button" aria-expanded="false" aria-controls="collapseEnd" style="background: #5A1EB8;border-radius: 20px;">ПОКАЗАТЬ/CКРЫТЬ</a>
      </div>
      </div>


      </form>



      <div class="row">
      </div>

      <!--





	<p id="end">Завершенные проекты</p>

    <form method="post" class="compl">
        	{% csrf_token %}
        	<div class="completeform">
        	<input type="checkbox" id="button3">
            <div class="xpandable-block_c">
            <div class="tab">
            	<table class="table_blur_compl">
            		<tbody>
                		<tr class="name">
                        	<td>Клиент</td>
                        	<td>Название РК</td>
                        	<td>Бюджет</td>
                        	<td>Период</td>
                        	<td>Карточка проекта</td>
                        </tr>
            			{% for name in complete %}
                    	<tr>
                        	<td>{{name.client}}</td>
                        	<td>{{name.name_rk}}</td>
                        	<td>{{name.budget}}</td>
                        	<td>{{name.period_c}} - {{name.period_p}}</td>
                            <td>
                                <a class="s3" href="{% url 'exel:but_cleared' %}">Карточка проекта</a>
                            </td>
                		</tr>
                	{% endfor %}
            	</tbody>
            </table>
        </div>
        </div>
        <label class="label" for="button3">ПОКАЗАТЬ/CКРЫТЬ</label>
        </div>
	</form>
    <div id="end">
    </div>
-->






  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
   


<script>

M.AutoInit();

document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.collapsible');
    var instances = M.Collapsible.init(elems, options);
  });


  </script>
{% endblock %}
  </body>

</html>

exel/templates/but_cleared.html
{% extends 'download_calc.html' %}

{% load static %}

{% block title %}Клиент {{file.client}}{% endblock %}

{% block content %}
    <div class="preloader">
    <div class="preloader__row">
      <div class="preloader__item"></div>
      <div class="preloader__item"></div>
    </div>
  </div>
    
    <div class="clear">
    <a href="{% url 'exel:main' %}" class="button">Главная</a>
	<form method="post" enctype="multipart/form-data" id="cl">
	{% csrf_token %}
		<hr class="hr1">
		<h3>Название клиента</h3>
            <h3>{{file.client}}</h3>
		<div class="cl">
        	<h3>Название PK</h3>
            {{form1.name_rk}}
           	<hr>
        	<h3>Медиаплан (файл)</h3>
        	<a href="{{file.mp.url}}">Выгрузить</a> 
        	{{form1.mp}}
        	<hr>
        	<h3>Доступы к GTM и т.п.</h3>
        	{{form1.access}}
        	<hr>
        	<h3>Ссылка на сайт (посадочная) Utm (файл)</h3>
        	{{form1.landing}}
        	<a class="button2" href="{% url 'exel:utm' file.name_rk %}">Utm</a>
        	<hr>
        	<h3>Материалы (файлы)</h3>
        	<a class="five" href="{% url 'exel:materials' file.name_rk %}">просмотр</a>
        	<hr>
        	<h3>Статус запуска (списком)</h3>
        	{{form1.comments}}
        	<hr>
    	</div>
    	<input class="button1" type="submit" name="form1" value="Сохранить изменения">

	</form>
	{{e1}}
	{{e2}}
	<p id="rk">Статистика по РК</p>
	{%for r in report%}
        <a class="s131" href="{{ r.file.url }}">Шаблон отчета, который надо заполнять</a>
    {%endfor%}
    
    <form  method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{form2.report}}
        <input type="submit" name="form2" class="button3" value="Загрузить отчет">
        <a href="{% url 'exel:complete' file.name_rk %}" class="button2" id="complete">Завершить проект</a>
	</form>
	
    </div>
    <script>
    window.onload = function () {
      document.body.classList.add('loaded_hiding');
      window.setTimeout(function () {
        document.body.classList.add('loaded');
        document.body.classList.remove('loaded_hiding');
      }, 500);
    }
  </script>
{% endblock %}

exel/templates/materials.html
{% extends 'download_calc.html' %}

{% load static %}

{% block title %}Материалы{% endblock %}

{% block content %}

    <a href="{% url 'exel:but_cleared' name_rk %}" class="button" id="back">Назад</a>

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form_materials">
        {{ form }}
        <input type="submit" class="mat" value="загрузить"/>
        </div>

        <div class="formtable1">
        	<input type="checkbox" id="button1">
            <div class="xpandable-block_m">
            <div class="tab">
            	<table class="table_blur">
                    {% for i in files %}
                        {% for k in i %}
                            <tr>
                            <td>
                                <a href={{k.file.url}} class="materials">{{k.file.name}}</a>
                            </td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                <tbody>
            </table>
        </div>
        </div>
        <label class="labeltable" for="button1">Показатать/Cкрыть</label>
        </div>
    </form>



{% endblock %}